name: flutter_sound_web
version: 10.3.6
description: Flutter plugin that relates to sound like audio and recorder.
#author: canardoux<larpoux@gmail.com>
homepage:  https://tau-ver.canardoux.xyz/fs-README.html
repository: https://github.com/canardoux/flutter_sound_web/

environment:
    sdk: ^3.3.0
    flutter: ">=2.0.0"

# 0.1.y+z is compatible with 1.0.0, if you land a breaking change bump
# the version to 2.0.0.
# See more details: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterSoundPlugin
        fileName: flutter_sound_web.dart
        
  assets:
  - howler/howler.js
  - src/flutter_sound.js
  - src/flutter_sound_player.js
  - src/flutter_sound_recorder.js
  - src/flutter_sound_stream_processor.js

dependencies:
  flutter_sound_platform_interface: 10.3.6
#    path: ../flutter_sound_platform_interface # Flutter Sound Dir

##  etau: ^0.0.14-alpha.5
##    path: ../../tau/etau # etau Dir

##  tau_web: ^0.0.14-alpha.5
##    path: ../../tau/tau_web # tau_web Dir
    
  flutter:
    sdk: flutter
  logger: ^2.0.2
  flutter_web_plugins:
    sdk: flutter
  web: '>=0.5.0 <2.0.0'


dev_dependencies:
  flutter_test:
    sdk: flutter
 
